# Generated by Django 4.1.2 on 2022-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('vendor', 'vendor'), ('baker', 'baker'), ('client', 'client')], default='client', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'director')), fields=('role',), name='unique_director_role'),
        ),
    ]
