# Generated by Django 4.1.2 on 2022-11-15 15:01

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.managers.StaffManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_director_role',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'director')), fields=('role',), name='bitta_direktor'),
        ),
    ]
