# Generated by Django 4.1.2 on 2022-11-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_remove_user_unique_director_role_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaditem',
            old_name='count',
            new_name='count_come',
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='breaditem',
            name='image',
        ),
        migrations.AddField(
            model_name='bread',
            name='image',
            field=models.ImageField(default=1, upload_to='bread/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaditem',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='breaditem',
            name='count_last',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bread', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='breaditem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bread_item', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='main.category'),
        ),
    ]
