# Generated by Django 4.1.2 on 2022-11-14 13:26

from django.db import migrations, models
import django.db.models.deletion
import main.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'new'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('success', 'success')], default='new', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='accounts.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('count', models.PositiveIntegerField()),
                ('price', models.FloatField(validators=[main.services.validate_amount])),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='main.bread')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
